# Generated by Django 5.1.3 on 2024-11-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=200)),
                ("project_description", models.TextField()),
                ("project_image", models.ImageField(upload_to="project_images")),
                ("project_link", models.URLField()),
                ("project_github_link", models.URLField()),
            ],
        ),
    ]
