# Generated by Django 5.1.3 on 2024-11-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_project_created_date_project_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_image",
            field=models.ImageField(blank=True, null=True, upload_to="project_images"),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
